### ISSUE TITLE
Swallows all unhandled errors and exceptions from custom server when used as module

### ISSUE THREAD

**Issue by simenbrekken** [popeindustries/dvlp#251]
When an application is started handlers are registered for unhandled exceptions and rejections (https://github.com/popeindustries/dvlp/blob/master/src/server/server.js#L369-L371). The handler uses `fatal` from the `log` utility (https://github.com/popeindustries/dvlp/blob/master/src/server/server.js#L458-L460) that is only enabled when invoking `dvlp` via it's binary. (https://github.com/popeindustries/dvlp/blob/master/src/utils/log.js#L17)

**Comment by popeindustries** [comment]
What is the desired behaviour when running dvlp directly via the JS API? Should we drop `disabled`? Ideally, we should probably delegate to the controlling process via an `error` event: `server.on('error', ...)`

**Comment by simenbrekken** [comment]
It took me quite some time figuring out why no errors were logged during transpilation. Maybe a solution could be renaming `disabled` to `silent` and have it follow the `silent` flag?
