### ISSUE TITLE
Add SSL support

### ISSUE THREAD

**Issue by simenbrekken** [popeindustries/dvlp#339]
- Accept `--ssl <path to folder containing .crt and .key>` parameter
- use `https.createServer` (see See https://github.com/nrkno/nrk-tv-web/blob/main/packages/dev-server/index.js#L75-L98)
- Print hostname and warn if cert has expired: `openssl x509 -noout -subject -dates -in <path to crt>`

**Comment by popeindustries** [comment]
here's a crt parser that doesn't require openssl: https://github.com/Southern/node-x509

**Comment by simenbrekken** [comment]
> here's a crt parser that doesn't require openssl: https://github.com/Southern/node-x509

Written in C though...

**Comment by simenbrekken** [comment]
Maybe https://github.com/fidm/x509?

**Comment by popeindustries** [comment]
Better. Nice if we can do this cross-platform
