### ISSUE TITLE
Add support for multiple mock arguments

### ISSUE THREAD

**Issue by simenbrekken** [popeindustries/dvlp#348]
It would be nice to be able to specify multiple arguments to `--mock` e.g.: `--mock mocks/auth mocks/some-broken-api`

**Comment by popeindustries** [comment]
aha! we already have that. From the docs:

Register mocked responses with the command-line option `-m, --mock` and a path to your mock files:

```json
{
  "scripts": {
    "dev": "dvlp --mock path/to/mock/files --port 8000 src/app.js"
  }
}
```

Your `path/to/mock/files` could be one of the following:

- path to directory of files: `path/to/mock/directory`
- path to a single file: `path/to/mock.json`

(_Note that the following require wrapping in `""`_)

- globbed path to multiple files/directories: `"path/to/mock/{api,assets}"`
- multiple files/directories separated by space, `,`, or `;`: `"path/to/mock1.json, path/to/mock2.json"`
