### ISSUE TITLE
Merged mock-headers are case-sensitive

### ISSUE THREAD

**Issue by ingvilddev** [popeindustries/dvlp#356]
Should be normalized when merged:
![image](https://user-images.githubusercontent.com/72200992/95854482-50921980-0d57-11eb-9042-0c0404a4a249.png)

Mocked response then was this in network:
![image](https://user-images.githubusercontent.com/72200992/95854567-6dc6e800-0d57-11eb-8321-16f7c6d310ad.png)

**Comment by popeindustries** [comment]
That's a good point, though one might consider that a user error. With respect to `Date` specifically, it's actually overwritten, so it wouldn't work anyway! It's probably a bit problematic to have hard-coded `Date` headers in static mock files, but I can see the use case for dynamic mocks. Not sure what is best, but I suppose that if a user has specified a `Date`, it should be respected.
