### ISSUE TITLE
package.json 'exports' points to non-existant directory 'src'

### ISSUE THREAD

**Issue by knuthaug** [popeindustries/dvlp#525]
Yo, mr. @popeindustries 

When trying to upgrade to 15.0.0 the build fails due to problems resolving some files. 

For example importing testBrowser with

```
import { testBrowser } from 'dvlp/dvlp-test-browser.js';
```

Gives an error in resolving the file

```
The module "./src/dvlp-test-browser.js" was not found on the file system
```
Most likely because the exports config in the `package.json` points to `src` folder, which is not included in the built package. 

"exports": {
    ".": "./src/dvlp.js",
    "./resolver": "./src/resolver/index.js",
    "./test-browser": "./src/dvlp-test-browser.js",
    "./dvlp-test-browser.js": "./src/dvlp-test-browser.js",
    "./test": "./src/dvlp-test.js",
    "./dvlp-test.js": "./src/dvlp-test.js"
  }
```

**Comment by popeindustries** [comment]
Ah, sorry. I think I published with `npm publish` instead of `pnpm publish`, and the `publishConfig` settings weren't applied.
